
GO
 -- 1 -- 
 -- VehicleType -- 

GO
IF EXISTS ( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE  TABLE_NAME='VehicleType' AND COLUMN_NAME='nVechicleTypeID' ) BEGIN 		ALTER TABLE VehicleType		ALTER COLUMN nVechicleTypeID numeric(18,0)  NOT NULL  END  

GO
IF EXISTS ( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE  TABLE_NAME='VehicleType' AND COLUMN_NAME='sVehicleTypeName' ) BEGIN 		ALTER TABLE VehicleType		ALTER COLUMN sVehicleTypeName varchar(100)  NULL  END  

GO
IF EXISTS ( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE  TABLE_NAME='VehicleType' AND COLUMN_NAME='sVehicleTypeCode' ) BEGIN 		ALTER TABLE VehicleType		ALTER COLUMN sVehicleTypeCode varchar(10)  NULL  END  

GO
IF EXISTS ( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE  TABLE_NAME='VehicleType' AND COLUMN_NAME='dtCreatedDate' ) BEGIN 		ALTER TABLE VehicleType		ALTER COLUMN dtCreatedDate datetime  NULL  END  

GO
IF EXISTS ( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE  TABLE_NAME='VehicleType' AND COLUMN_NAME='dtModifiedDate' ) BEGIN 		ALTER TABLE VehicleType		ALTER COLUMN dtModifiedDate datetime  NULL  END  



GO
 -- 2 -- 
 -- PartyType -- 

GO
IF EXISTS ( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE  TABLE_NAME='PartyType' AND COLUMN_NAME='nPartyTypeID' ) BEGIN 		ALTER TABLE PartyType		ALTER COLUMN nPartyTypeID numeric(18,0)  NOT NULL  END  

GO
IF EXISTS ( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE  TABLE_NAME='PartyType' AND COLUMN_NAME='sPartyTypeName' ) BEGIN 		ALTER TABLE PartyType		ALTER COLUMN sPartyTypeName varchar(100)  NULL  END  

GO
IF EXISTS ( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE  TABLE_NAME='PartyType' AND COLUMN_NAME='sPartyTypeCode' ) BEGIN 		ALTER TABLE PartyType		ALTER COLUMN sPartyTypeCode varchar(10)  NULL  END  

GO
IF EXISTS ( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE  TABLE_NAME='PartyType' AND COLUMN_NAME='dtCreatedDate' ) BEGIN 		ALTER TABLE PartyType		ALTER COLUMN dtCreatedDate datetime  NULL  END  

GO
IF EXISTS ( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE  TABLE_NAME='PartyType' AND COLUMN_NAME='dtModifiedDate' ) BEGIN 		ALTER TABLE PartyType		ALTER COLUMN dtModifiedDate datetime  NULL  END  



GO
 -- 3 -- 
 -- MaterialType -- 

GO
IF EXISTS ( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE  TABLE_NAME='MaterialType' AND COLUMN_NAME='nMaterialTypeID' ) BEGIN 		ALTER TABLE MaterialType		ALTER COLUMN nMaterialTypeID numeric(18,0)  NOT NULL  END  

GO
IF EXISTS ( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE  TABLE_NAME='MaterialType' AND COLUMN_NAME='sMaterialTypeName' ) BEGIN 		ALTER TABLE MaterialType		ALTER COLUMN sMaterialTypeName varchar(100)  NULL  END  

GO
IF EXISTS ( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE  TABLE_NAME='MaterialType' AND COLUMN_NAME='sMaterialTypeCode' ) BEGIN 		ALTER TABLE MaterialType		ALTER COLUMN sMaterialTypeCode varchar(10)  NULL  END  

GO
IF EXISTS ( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE  TABLE_NAME='MaterialType' AND COLUMN_NAME='dtCreatedDate' ) BEGIN 		ALTER TABLE MaterialType		ALTER COLUMN dtCreatedDate datetime  NULL  END  

GO
IF EXISTS ( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE  TABLE_NAME='MaterialType' AND COLUMN_NAME='dtModifiedDate' ) BEGIN 		ALTER TABLE MaterialType		ALTER COLUMN dtModifiedDate datetime  NULL  END  



GO
 -- 4 -- 
 -- Designation -- 

GO
IF EXISTS ( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE  TABLE_NAME='Designation' AND COLUMN_NAME='nDesignationID' ) BEGIN 		ALTER TABLE Designation		ALTER COLUMN nDesignationID numeric(18,0)  NOT NULL  END  

GO
IF EXISTS ( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE  TABLE_NAME='Designation' AND COLUMN_NAME='sDesignationName' ) BEGIN 		ALTER TABLE Designation		ALTER COLUMN sDesignationName varchar(100)  NULL  END  

GO
IF EXISTS ( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE  TABLE_NAME='Designation' AND COLUMN_NAME='bIsAllowAccess' ) BEGIN 		ALTER TABLE Designation		ALTER COLUMN bIsAllowAccess bit  NULL  END  

GO
IF EXISTS ( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE  TABLE_NAME='Designation' AND COLUMN_NAME='bIsAllowSignatory' ) BEGIN 		ALTER TABLE Designation		ALTER COLUMN bIsAllowSignatory bit  NULL  END  

GO
IF EXISTS ( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE  TABLE_NAME='Designation' AND COLUMN_NAME='sDesignationCode' ) BEGIN 		ALTER TABLE Designation		ALTER COLUMN sDesignationCode varchar(10)  NULL  END  

GO
IF EXISTS ( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE  TABLE_NAME='Designation' AND COLUMN_NAME='dtCreatedDate' ) BEGIN 		ALTER TABLE Designation		ALTER COLUMN dtCreatedDate datetime  NULL  END  

GO
IF EXISTS ( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE  TABLE_NAME='Designation' AND COLUMN_NAME='dtModifiedDate' ) BEGIN 		ALTER TABLE Designation		ALTER COLUMN dtModifiedDate datetime  NULL  END  



GO
 -- 5 -- 
 -- CompanyType -- 

GO
IF EXISTS ( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE  TABLE_NAME='CompanyType' AND COLUMN_NAME='nCompanyTypeID' ) BEGIN 		ALTER TABLE CompanyType		ALTER COLUMN nCompanyTypeID numeric(18,0)  NOT NULL  END  

GO
IF EXISTS ( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE  TABLE_NAME='CompanyType' AND COLUMN_NAME='sCompanyTypeName' ) BEGIN 		ALTER TABLE CompanyType		ALTER COLUMN sCompanyTypeName varchar(100)  NULL  END  

GO
IF EXISTS ( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE  TABLE_NAME='CompanyType' AND COLUMN_NAME='sCompanyTypeCode' ) BEGIN 		ALTER TABLE CompanyType		ALTER COLUMN sCompanyTypeCode varchar(10)  NULL  END  

GO
IF EXISTS ( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE  TABLE_NAME='CompanyType' AND COLUMN_NAME='dtCreatedDate' ) BEGIN 		ALTER TABLE CompanyType		ALTER COLUMN dtCreatedDate datetime  NULL  END  

GO
IF EXISTS ( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE  TABLE_NAME='CompanyType' AND COLUMN_NAME='dtModifiedDate' ) BEGIN 		ALTER TABLE CompanyType		ALTER COLUMN dtModifiedDate datetime  NULL  END  



GO
 -- 6 -- 
 -- AssetMainType -- 

GO
IF EXISTS ( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE  TABLE_NAME='AssetMainType' AND COLUMN_NAME='nAssetMainTypeID' ) BEGIN 		ALTER TABLE AssetMainType		ALTER COLUMN nAssetMainTypeID numeric(18,0)  NOT NULL  END  

GO
IF EXISTS ( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE  TABLE_NAME='AssetMainType' AND COLUMN_NAME='sAssetType' ) BEGIN 		ALTER TABLE AssetMainType		ALTER COLUMN sAssetType varchar(100)  NULL  END  

GO
IF EXISTS ( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE  TABLE_NAME='AssetMainType' AND COLUMN_NAME='sAssetCode' ) BEGIN 		ALTER TABLE AssetMainType		ALTER COLUMN sAssetCode varchar(10)  NULL  END  

GO
IF EXISTS ( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE  TABLE_NAME='AssetMainType' AND COLUMN_NAME='bIsSystemDefined' ) BEGIN 		ALTER TABLE AssetMainType		ALTER COLUMN bIsSystemDefined bit  NULL  END  

GO
IF EXISTS ( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE  TABLE_NAME='AssetMainType' AND COLUMN_NAME='dtCreatedDate' ) BEGIN 		ALTER TABLE AssetMainType		ALTER COLUMN dtCreatedDate datetime  NULL  END  

GO
IF EXISTS ( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE  TABLE_NAME='AssetMainType' AND COLUMN_NAME='dtModifiedDate' ) BEGIN 		ALTER TABLE AssetMainType		ALTER COLUMN dtModifiedDate datetime  NULL  END  



GO
 -- 7 -- 
 -- AssetType -- 

GO
IF EXISTS ( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE  TABLE_NAME='AssetType' AND COLUMN_NAME='nAssetTypeID' ) BEGIN 		ALTER TABLE AssetType		ALTER COLUMN nAssetTypeID numeric(18,0)  NOT NULL  END  

GO
IF EXISTS ( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE  TABLE_NAME='AssetType' AND COLUMN_NAME='sAssetTypeName' ) BEGIN 		ALTER TABLE AssetType		ALTER COLUMN sAssetTypeName varchar(100)  NULL  END  

GO
IF EXISTS ( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE  TABLE_NAME='AssetType' AND COLUMN_NAME='nAssetMainTypeID' ) BEGIN 		ALTER TABLE AssetType		ALTER COLUMN nAssetMainTypeID numeric(18,0)  NULL  END  

GO
IF EXISTS ( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE  TABLE_NAME='AssetType' AND COLUMN_NAME='sAssetTypeCode' ) BEGIN 		ALTER TABLE AssetType		ALTER COLUMN sAssetTypeCode varchar(10)  NULL  END  

GO
IF EXISTS ( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE  TABLE_NAME='AssetType' AND COLUMN_NAME='dtCreatedDate' ) BEGIN 		ALTER TABLE AssetType		ALTER COLUMN dtCreatedDate datetime  NULL  END  

GO
IF EXISTS ( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE  TABLE_NAME='AssetType' AND COLUMN_NAME='dtModifiedDate' ) BEGIN 		ALTER TABLE AssetType		ALTER COLUMN dtModifiedDate datetime  NULL  END  



GO
 -- 8 -- 
 -- AssetTypeOne -- 

GO
IF EXISTS ( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE  TABLE_NAME='AssetTypeOne' AND COLUMN_NAME='nAssetTypeOneID' ) BEGIN 		ALTER TABLE AssetTypeOne		ALTER COLUMN nAssetTypeOneID numeric(18,0)  NOT NULL  END  

GO
IF EXISTS ( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE  TABLE_NAME='AssetTypeOne' AND COLUMN_NAME='sAssetTypeOneName' ) BEGIN 		ALTER TABLE AssetTypeOne		ALTER COLUMN sAssetTypeOneName varchar(100)  NULL  END  

GO
IF EXISTS ( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE  TABLE_NAME='AssetTypeOne' AND COLUMN_NAME='nAssetMainTypeID' ) BEGIN 		ALTER TABLE AssetTypeOne		ALTER COLUMN nAssetMainTypeID numeric(18,0)  NULL  END  

GO
IF EXISTS ( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE  TABLE_NAME='AssetTypeOne' AND COLUMN_NAME='sAssetTypeOneCode' ) BEGIN 		ALTER TABLE AssetTypeOne		ALTER COLUMN sAssetTypeOneCode varchar(10)  NULL  END  

GO
IF EXISTS ( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE  TABLE_NAME='AssetTypeOne' AND COLUMN_NAME='dtCreatedDate' ) BEGIN 		ALTER TABLE AssetTypeOne		ALTER COLUMN dtCreatedDate datetime  NULL  END  

GO
IF EXISTS ( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE  TABLE_NAME='AssetTypeOne' AND COLUMN_NAME='dtModifiedDate' ) BEGIN 		ALTER TABLE AssetTypeOne		ALTER COLUMN dtModifiedDate datetime  NULL  END  



GO
 -- 9 -- 
 -- ColourType -- 

GO
IF EXISTS ( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE  TABLE_NAME='ColourType' AND COLUMN_NAME='nColourTypeID' ) BEGIN 		ALTER TABLE ColourType		ALTER COLUMN nColourTypeID numeric(18,0)  NOT NULL  END  

GO
IF EXISTS ( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE  TABLE_NAME='ColourType' AND COLUMN_NAME='sColourTypeName' ) BEGIN 		ALTER TABLE ColourType		ALTER COLUMN sColourTypeName varchar(100)  NULL  END  

GO
IF EXISTS ( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE  TABLE_NAME='ColourType' AND COLUMN_NAME='sColourTypeCode' ) BEGIN 		ALTER TABLE ColourType		ALTER COLUMN sColourTypeCode varchar(10)  NULL  END  

GO
IF EXISTS ( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE  TABLE_NAME='ColourType' AND COLUMN_NAME='dtCreatedDate' ) BEGIN 		ALTER TABLE ColourType		ALTER COLUMN dtCreatedDate datetime  NULL  END  

GO
IF EXISTS ( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE  TABLE_NAME='ColourType' AND COLUMN_NAME='dtModifiedDate' ) BEGIN 		ALTER TABLE ColourType		ALTER COLUMN dtModifiedDate datetime  NULL  END  



GO
 -- 10 -- 
 -- DensityType -- 

GO
IF EXISTS ( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE  TABLE_NAME='DensityType' AND COLUMN_NAME='nDensityTypeID' ) BEGIN 		ALTER TABLE DensityType		ALTER COLUMN nDensityTypeID numeric(18,0)  NOT NULL  END  

GO
IF EXISTS ( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE  TABLE_NAME='DensityType' AND COLUMN_NAME='sDensityTypeName' ) BEGIN 		ALTER TABLE DensityType		ALTER COLUMN sDensityTypeName varchar(100)  NULL  END  

GO
IF EXISTS ( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE  TABLE_NAME='DensityType' AND COLUMN_NAME='sDensityTypeCode' ) BEGIN 		ALTER TABLE DensityType		ALTER COLUMN sDensityTypeCode varchar(10)  NULL  END  

GO
IF EXISTS ( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE  TABLE_NAME='DensityType' AND COLUMN_NAME='dtCreatedDate' ) BEGIN 		ALTER TABLE DensityType		ALTER COLUMN dtCreatedDate datetime  NULL  END  

GO
IF EXISTS ( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE  TABLE_NAME='DensityType' AND COLUMN_NAME='dtModifiedDate' ) BEGIN 		ALTER TABLE DensityType		ALTER COLUMN dtModifiedDate datetime  NULL  END  


